version: "3.7"
services:
  app:
    build:
      args:
        user: erika
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: landing-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - landing

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - landing
  db:
    image: library/mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: landing-db
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      #MYSQL_USER: root
    networks:
      - landing
  phpmyadmin:
    image: library/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 9191:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123
      PMA_HOST: db
    networks:
      - landing
networks:
  landing:
    driver: bridge
